### ISSUE TITLE
Home Assistant automations don't include on/off capability

### ISSUE THREAD

**Issue by jcrowthe** [cdnninja/yoto_ha#101]
Hey, great integration with yoto! Thank you for taking the time to develop this.

An automation I am looking for is the ability to trigger a Yoto device to stop playing. To achieve this, I'd use Home Assistant's Automations. I am successfully able to specify "Yoto is playing" or "Yoto is on" for If conditions, but when it comes to actions, there is no action for controlling the Yoto's play/pause abilities.

Would this be a simple fix to add?

**Comment by cdnninja** [comment]
Right now Media player: Stop as a service call works for this integration. 

Are you looking for a stop command or power off the device?

**Comment by cdnninja** [comment]
Glad it works! Let me know if you need anything else.  I have slowed on updates for this since I have all I personally need but happy to add features if interest exists!
