### ISSUE TITLE
No longer working, Unexpected error

### ISSUE THREAD

**Issue by ctrlaltd1337ed** [cdnninja/yoto_ha#114]
All of my entities are showing as no longer available, and it is saying that the integration needs attention. The error I receive when I try to reload the integration:

> Failed setup, will retry: Config Not Ready: invalid literal for int() with base 10: 'notSupported'

I haven't changed anything, and I've updated when it asked, currently on 1.18.2, running on HAOS.

I tried to delete the link to my account, and log back in, but when I enter my login info, I am greeted with _Unexpected error_. I logged into the Yoto site to confirm that the password still works.

Some debug logs:

[home-assistant_yoto_2024-09-06T15-23-53.646Z.log](https://github.com/user-attachments/files/16910015/home-assistant_yoto_2024-09-06T15-23-53.646Z.log)

**Comment by cdnninja** [comment]
Could you try on the latest? Struggle has been real!

**Comment by ctrlaltd1337ed** [comment]
Deleted it and redownloaded through HACS, and still had the same issue.  

It still showed the same version, but I can see that the latest version was still 1.18.2, but at the same time I see that you've changed a few things in the repo. Would you have to re-release as a different version?

No rush on this at all, enjoy your weekend lol.

**Comment by cdnninja** [comment]
Oops! Try now.

**Comment by ctrlaltd1337ed** [comment]
1.18.3 allowed me to log in and all entities are working again. 

Cheers!
