### ISSUE TITLE
temp

### ISSUE THREAD

**Issue by cjb0001** [cdnninja/yoto_ha#12]
**Log details**

TEMP_CELSIUS was used from yoto, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please report it to the author of the 'yoto' custom integration

Entity sensor.abc_yoto_player_temperature (<class 'custom_components.yoto.sensor.YotoSensor'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('temperature') it is using; expected one of ['K', '°F', '°C']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/cdnninja/yoto_ha/issues

**Comment by cdnninja** [comment]
If you have cycles this is an easy fix and a good first one for you to do. Are you interested?

**Comment by cdnninja** [comment]
Solved this.
