### ISSUE TITLE
Entity not avalible

### ISSUE THREAD

**Issue by woodwai** [cdnninja/yoto_ha#130]
I have installed the integration, but no entities are available, and they don't appear as they do in the screen shots.

<img width="1440" alt="Screenshot 2024-10-28 at 19 09 38" src="https://github.com/user-attachments/assets/30315ea9-91ff-4d39-b7f6-1268dd71b755">

**Comment by cdnninja** [comment]
Could you enable debug logs and provide them?

**Comment by woodwai** [comment]
hope this is what you want.

[yoto.docx](https://github.com/user-attachments/files/17547857/yoto.docx)

**Comment by cdnninja** [comment]
Strange - reloading or restarting home assistant doesn't help?

**Comment by woodwai** [comment]
No, nothing changes

**Comment by cdnninja** [comment]
Just for kicks could you rename to remove the apostrophe from the device name in Yoto's app. Reload the integration and let me know if anything changes.

**Comment by woodwai** [comment]
Ive resolved it, it was a local network firewall issue

**Comment by cdnninja** [comment]
Enjoy the integration.  Let me know if you want anything added to it feature wise!
