### ISSUE TITLE
Max Volume Limits

### ISSUE THREAD

**Issue by wilhoits** [cdnninja/yoto_ha#134]
WHen trying to set the MAX DAY VOLUME or MAX NIGHT VOLUME limits, it only works for whole numbers from 1-16. It does not allow you to set as 0, though the player allows this to essentially mute the player. Can you please add the ability set the two MAX VOLUME settings to 0?

**Comment by cdnninja** [comment]
Good find!  I have a good idea of how to fix this.  I'll post back once solved.

**Comment by cdnninja** [comment]
1.20.2 should fix this.  I will rest when my kid isn't using it.

**Comment by cdnninja** [comment]
Tests out for me.  Let me know if works for you!

**Comment by The-Optimistic-Yack-Order** [comment]
Works for me, too! Thanks!
