### ISSUE TITLE
support for media_player.media_seek?

### ISSUE THREAD

**Issue by dangerusty** [cdnninja/yoto_ha#140]
I have a request to resume Yoto player last played media at the last played position, upon button press. So far, I have an automation to save the media_content_id and the media_position to helpers. I have another automation on button press to play_media with the media_content_id, but media_seek is unsupported. Is that possible?

**Comment by cdnninja** [comment]
I should be able to add media seek.   I'm not sure if that will resume between media to the spot you left off though.  Does it do that for other media integrations in HA?

**Comment by dangerusty** [comment]
Yes, I’ve just tested media player: seek on my Apple TV and it seeks to a different position.

**Comment by cdnninja** [comment]
I have added seek to the latest release.   Let me know if it works correctly for you.

**Comment by dangerusty** [comment]
When I send the seek action with the media_position, it switches to playing
and then idle immediately. Too fast to know if it tried at the given
position, unsure why it would not continue playing.

**Comment by cdnninja** [comment]
Is this with an automation? So a play call right before it? 

The seek command is actually a play command with a time added to it.  So an automation that plays followed by seek is two play commands back to back.

**Comment by dangerusty** [comment]
Yes, I had play and then seek. I just tried seek only, but it said the seek command doesn't allow key media_content_id. That's what I was using in the play action to resume whatever book was playing before (another automation saves media_content_id and media_position to helpers when Yoto stops playing).

**Comment by cdnninja** [comment]
Seek works for me but yes you can't pass content id.  I tested and it works for currently playing content.   It can't select.

Let me see if I can add a custom field on play content to have the start at time passed in a single command. 

I bet your automation would work if you waited between commands but that is clunky.

**Comment by dangerusty** [comment]
You're right, this works with a minimum 3 second delay. Thank you very much for working on this.

**Comment by cdnninja** [comment]
Looks like I can't add a value. Home assistant doesn't let me.  One solution is to leverage how I fixed the chapter aspect. 

Media ID for yoto is actually 3 parts.   Card, chapter and track.   Since I couldn't pass three fields you probably noticed I just used dashes.  The code checks for each item. If one is missing just starts at 1.  So if only card is passed it starts at the start of the card,  chapter 1.   If you pass chapter it obeys.  

I could add a forth element, time.  So card-chapter-track-starttime.   If start time is missing it would start at 0.  If present it would obey it.  

Thoughts?

**Comment by dangerusty** [comment]
That makes perfect sense to me

**Comment by cdnninja** [comment]
Done.  Latest version now supports an additional value of start time.   Let me know if that works and we can close this one out.

**Comment by dangerusty** [comment]
That works in one automation step now! Thank you.

**Comment by cdnninja** [comment]
Excellent glad to hear!
