### ISSUE TITLE
Integration errors when set up using an account that has no Yoto Players set up

### ISSUE THREAD

**Issue by Particpant** [cdnninja/yoto_ha#144]
If you set up the integration, provide valid credentials, but use an account without any players connected, it'll fail during setup. Disabling the integration, and re-enabling it after adding the players fixes it.
Apologies, I didn't get the logs, but the integration details _definitely_ indicated that there was an exception related to something not working right with futures.

Thanks for building this out, by the way! Appreciate it!

**Comment by cdnninja** [comment]
I don't see this being something worth fixing. Without a player in the account this integration doesn't have value.

**Comment by Particpant** [comment]
Agreed.
