### ISSUE TITLE
No temperature visible on v3e

### ISSUE THREAD

**Issue by bdavj** [cdnninja/yoto_ha#146]
Running on a v3e, temperature available in Yoto. Doesn't seem to be visible in HA (light etc work). 

Yoto v2.19.8, integration 1.22.0. 

Thanks for the great project!

**Comment by cdnninja** [comment]
Hmm my v3 shows temp.  Could you enable debug logs and provide them? 

As well could you see if restarting integration solves this.

**Comment by Particpant** [comment]
I've got two V3 models on Firmware: v2.19.8 1.22.0.
One stopped reporting temperature overnight, the other continues to report temp.
"This entity is no longer being provided by the yoto integration. If the entity is no longer in use, delete it in settings."
Restarting the integration didn't resolve the missing temp sensor.
Here's some logs:
[yoto log.txt](https://github.com/user-attachments/files/18267292/yoto.log.txt)

It does appear that one of them is having the sensor reported as unsupported from the Yoto side.
`'temperatureCelcius': 'notSupported'` vs `'temperatureCelcius': '20'`

Rebooting the yoto itself, though, and then reloading the integration did seem to fix the temp sensor.

**Comment by cdnninja** [comment]
All good!  Sounds like this may be a firmware bug.  Good find!
