### ISSUE TITLE
To Do: Real time media player updates

### ISSUE THREAD

**Issue by cdnninja** [cdnninja/yoto_ha#31]
Need to add real time media player updates.   Data exists in the object just not displayed until next poll.

**Comment by cjb0001** [comment]
I propose changing manifest.json | "iot_class": "cloud_polling" to "cloud_push" which is what other integrations that get updates from MQTT are doing.
ref. [https://developers.home-assistant.io/docs/creating_integration_manifest/](https://developers.home-assistant.io/docs/creating_integration_manifest/)

**Comment by cdnninja** [comment]
I'll add that to my pr once I get it figured out for making HA update state properly.    Right now it only updates on the poll even though data has been processed and ready to go from mqtt.

**Comment by cjb0001** [comment]
related? [https://github.com/tolwi/hassio-ecoflow-cloud/pull/234#pullrequestreview-2039093981](https://github.com/tolwi/hassio-ecoflow-cloud/pull/234#pullrequestreview-2039093981)

**Comment by cdnninja** [comment]
A little bit yes.    Those commands are within the entity.  I am placing the call in the coordinator.  It is exactly what I need but can't find a way to pass this to the entity.

**Comment by cdnninja** [comment]
Real time updates are working!
