### ISSUE TITLE
To Do:  Light control and night day time config

### ISSUE THREAD

**Issue by cdnninja** [cdnninja/yoto_ha#33]
This one needs someone to find the POST api endpoint.

**Comment by cjb0001** [comment]
https://github.com/cdnninja/yoto_api/discussions/5#discussioncomment-9448567

**Comment by cdnninja** [comment]
Thank you!   Time sensors now show up but I haven't got to the set part just yet.   Color will also take a bit since I think I should add those as a "light" entity for both on off and color control.

**Comment by cjb0001** [comment]
For the set part, note a PUT request should be sent, not POST.

**Comment by cdnninja** [comment]
So turns out these devices support any color.  Not just those few in the app!

**Comment by cdnninja** [comment]
Time set for modes is now in master and functional. The config set function is build for the 8 items I think will be most in demand.  Easy to add others too.   My next focus will be adding the light control and those other items, max volume settings, brightness etc.

**Comment by cdnninja** [comment]
Few more config control items just added.  Including day and night max volume and brightness.   Auto brightness needs to be added still.

**Comment by WhimsySpoon** [comment]
Looks good! Just updated to latest master and had a quick play. Didn't realise my partner was putting our son to bed and she wondered what was happening as I was changing volume in a different room!

It would be good to have different icons for the values rather than the default slider ones to help differentiate them. I'm happy to work on that.

**Comment by cdnninja** [comment]
Great thank you!

**Comment by WhimsySpoon** [comment]
Here you go. These seemed like sensible choices for the icons, but happy to change them: https://github.com/cdnninja/yoto_ha/pull/76

**Comment by cdnninja** [comment]
Auto brightness switch now added.  I didn't do icons but have the switch working.

**Comment by WhimsySpoon** [comment]
> I didn't do icons

More than happy to help where I can - https://github.com/cdnninja/yoto_ha/pull/79

**Comment by cdnninja** [comment]
Appreciated!! 

Last few items I plan to do for control are the night light color and sleep timer.  After that I think all the key control features are done.   

Browse media is probably the other, that looks complicated in home assistant code though.

**Comment by WhimsySpoon** [comment]
It's amazing how quickly this integration has come out of nothing. Great work to all involved!

Personally, I wouldn't get a huge amount of value from Browse Media, but it would be good to play a card/track from a service call.

**Comment by cdnninja** [comment]
Play media works today. You can't input a track. I hard coded it to the first track to get it working.  

If you go to service call and enter the card id it will work.

**Comment by WhimsySpoon** [comment]
Ah excellent. I'll have a play tomorrow and update the readme with more details.

**Comment by cdnninja** [comment]
Light control for day/night was this weeks config item.   As a note works for all colors not just the short list in app.   I am going to close this out now since key control items are complete.  Alarms may make sense in the future but will wait for interest first.
