### ISSUE TITLE
Unable to add as HACS custom repo

### ISSUE THREAD

**Issue by jvik** [cdnninja/yoto_ha#36]
![image](https://github.com/cdnninja/yoto_ha/assets/17274215/b9aa2bdd-ed38-4b3d-9327-6a971408fe50)

Error: No RepositoryFile.MAINIFEST_JSON file found 'custom_components/yoto/RepositoryFile.MAINIFEST_JSON'

**Comment by cdnninja** [comment]
I just retried and adding works fine for me.  I added a screenshot to the readme.   Could you restart HA and try again?

**Comment by jvik** [comment]
Strange. Still same problem, even after updating home assistant and the hassio os. Doing it exactly as you have suggested in readme.

**Comment by cdnninja** [comment]
Any advanced firewalls setup?  Other option is copying the files by hand but then you won't get updates automatically

**Comment by cdnninja** [comment]
When googling this seems to be a HACS issue and a few ways to fix it referenced.  Deleting the Yoto integration folder being one.  

Did you try copy the files by hand prior to this?  Maybe worth checking if the folder exists.

**Comment by cdnninja** [comment]
Any word if this works for you now?

**Comment by jvik** [comment]
Suddenly just works now. Possibly after an OS upgrade. Thanks a lot.
