### ISSUE TITLE
enhancement: media_player media title improvement

### ISSUE THREAD

**Issue by cjb0001** [cdnninja/yoto_ha#48]
In cases where chapterTitle and trackTitle are not the same, adjust "media_title" to be "chapterTitle - trackTitle"
	  and add both chapterTitle and mediaTitle to the media_player attributes

`2024-05-19 13:39:16.309 DEBUG (Thread-2 (_thread_main)) [yoto_api.YotoMQTTClient] yoto_api - MQTT Message: {"trackLength":989,"position":383,"cardId":"ecnOg","repeatAll":false,"source":"remote","cardUpdatedAt":"2022-01-11T13:07:31.455Z","chapterTitle":"Chapter 1","chapterKey":"01","trackTitle":"Show and Tell","trackKey":"01","streaming":false,"volume":7,"volumeMax":16,"playbackStatus":"playing","playbackWait":false,"sleepTimerActive":false,"eventUtc":1716118754}`

**Comment by cdnninja** [comment]
Just as an example are you thinking "Card - Chapter" when they don't match?

**Comment by cdnninja** [comment]
Is this what you had in mind? 

https://github.com/cdnninja/yoto_ha/pull/52

**Comment by cjb0001** [comment]
perfect.

**Comment by cjb0001** [comment]
perfect.
