### ISSUE TITLE
enhancement: simplify media_player entity name

### ISSUE THREAD

**Issue by cjb0001** [cdnninja/yoto_ha#49]
Rename the media player entity from "media_player.users_yoto_player_media_player" to "media_player.users_yoto_player"

**Comment by cdnninja** [comment]
This will be a quick fix.  Thanks for raising it!

**Comment by cdnninja** [comment]
I believe this is done.  To test I have to delete and readd. I haven't done that yet.  Names are manually changed once installed I believe.

**Comment by WhimsySpoon** [comment]
I just installed the latest version of master via HACS, rebooted, deleted the integration and re-added and the media_player entities still have `_media_player` appended to their names.

**Comment by WhimsySpoon** [comment]
This is still an issue in 1.10.6.
