### ISSUE TITLE
Color Control Feedback

### ISSUE THREAD

**Issue by cdnninja** [cdnninja/yoto_ha#65]
I wanted to get peoples thoughts.  

From a yoto API standpoint from what I know: 

1. You can set any color on the v3 player. Not just the few in app.  I can pass RGB to it and it works.  
2. The API never reports the color displayed. So when I set the above I can't later confirm it. If changed via app I wouldn't know. 
3. I can however see and set the day and night configuration.   When this changes it resets the above RGB value based on if it is daytime or nighttime. 

So my question is how should I expose these controls? 
1. A Light entity that lets you pick the current color.  It would have to assume it worked and wouldn't update. 
2. A night and day light entity that just lets you pick the support color list. 
3. A service call that can set any color plus a light entity for day and night?  

A combo of the above? 

Struggling with this since I don't get values back on what color is shown so will make the interface less responsive than I would like.  I can however see "night light mode" which is a value that I don't understand.  It is displayed today.

**Comment by WhimsySpoon** [comment]
With option 2, if one was to change the value of the entity for the night version whilst that mode is active, would it immediately change the colour of the light?

**Comment by cdnninja** [comment]
Yes, those would the same as what's exposed in the native app.

**Comment by LOTRtelcontar** [comment]
I like the idea of being able to choose any color. Always annoyed me that the Yoto app only give you a few options and you also can’t changed them throughout the day. Would be great to use as a notification system or even sync to change the color with certain cards or even tracks.

**Comment by cdnninja** [comment]
Color control for day night now is complete.   It works for any color as well, the native app doesn't like when you set one not in the list, just shows off.   It works though.   

Two things I could add. 
1. A drop down list for day / night with the list of native colors.
2. A service item to change the current color without changing day night.  Would work for temp override.  The APIs exist for this.
