### ISSUE TITLE
Login not working

### ISSUE THREAD

**Issue by bushbrother** [cdnninja/yoto_ha#7]
Bringing this over from the "dev" discussion on yoto_api repo.

I have downloaded the yoto_ha integration via HACS by adding a custom repository, reboot HA and then add the new service, when entering login details it fails. I have triple checked credentials and even used them to run the yoto_api manually (which worked).

No logs in HA as the integration isnt even loaded/started. Happy to do any testing you need.

Core - 2024.4.3
Supervisor - 2024.04.0
Frontend - 20240404.2

**Comment by cdnninja** [comment]
Oops looks like if I deleted and re-added I had the same issue!  

Please try v1.0.1.

**Comment by bushbrother** [comment]
I updated to v1.1.0 and it works perfectly! You have moved on quite a bit in this version!! I will see if I can find time/skills to help out.

Anything to try focus on?
