### ISSUE TITLE
Add the ability to stop the playback

### ISSUE THREAD

**Issue by wilfriedroset** [cdnninja/yoto_ha#71]
Currently the control allow to play/pause the playback.
Would it be possible to add the stop button as well in the control?

<img width="328" alt="Capture d’écran 2024-05-30 à 23 22 18" src="https://github.com/cdnninja/yoto_ha/assets/12611310/a5e3fd27-cb8c-46e4-98e1-04bb23f651ed">

<img width="324" alt="Capture d’écran 2024-05-30 à 23 23 35" src="https://github.com/cdnninja/yoto_ha/assets/12611310/fcb33df6-f08b-4875-82f9-a8e228f530c6">

I'm using a v2 yoto with 1.12.2 integration

**Comment by cdnninja** [comment]
Hmm. I noticed I don't have the button either but the code exists to support it.  Service call exists and I think it works.  Do you have another integration example that has the stop button?

**Comment by wilfriedroset** [comment]
No i don't have any other integration with playback options. I will try to find one that i can use

**Comment by cdnninja** [comment]
Okay.  I think this just may be a home assistant thing.  The service should work which means you can add a button to your dashboard that does this.
